version: '3'
volumes:
  blynk-data:
  blynk-logs:
services:
  blynk:
    image: hortio/blynk:latest
    command: ["-dataFolder", "/data", "-serverConfig", "/blynk/server.properties"]
    volumes: 
      - 'blynk-data:/data' 
      - 'blynk-logs:/blynk/logs'
      - './mail.properties:/blynk/mail.properties'
      - './server.properties:/blynk/server.properties'
    ports:
      - "8080:8080" 
      - "9443:9443"
      ## If you don't want Let's encrypt certificates or have a reverse proxy on port 80,
      ## please comment out line below
      ##- "80:8080"
    restart: always  
